var petDog = 'Rex';
var petCat = 'Pepper';

console.log(petDog);
console.log(petCat);

console.log("My pet dog's name is: " + petDog);
console.log("My pet cat's name is: " + petCat);

var catSound = "purr";
var dogSound = "woof";

console.log(petDog, "says", dogSound);
console.log(petCat, "says", catSound);

var catSound = "Meow"; 
var dogSound = "Bark";

console.log(petCat, "now says", catSound);
console.log(petDog, "now says", dogSound);